#!/usr/bin/env node
/**
 * Build pipeline for the LoxBerry plugin ZIP.
 *
 *   icons → npm run build (esbuild bundle in `service/dist/service.mjs`)
 *   → dist-staging/maveoconnect (canonical LoxBerry layout)
 *   → dist/loxberry-plugin-maveoconnect-<VERSION>.zip
 *
 * Layout in the ZIP (see https://wiki.loxberry.de/.../start - "Aufbau der ZIP-Datei"):
 *   maveoconnect/
 *     plugin.cfg
 *     pre*.sh / post*.sh                   ← installer hooks
 *     webfrontend/htmlauth/...             ← PHP UI
 *     icons/icon_*.png                     ← plugin icons
 *     bin/service.mjs                      ← Node bundle (LoxBerry → /opt/loxberry/bin/plugins/maveoconnect/)
 *     daemon/daemon                        ← LSB init script (LoxBerry → /opt/loxberry/system/daemons/plugins/maveoconnect)
 *     sudoers/sudoers                      ← grants loxberry rootless restart of the init script
 *     uninstall/uninstall                  ← stop daemon on uninstall
 *
 * Empty directory entries are emitted explicitly to dodge LoxBerry / unzip quirks
 * around mkdir-on-extract.
 */
import fs from "node:fs";
import path from "node:path";
import archiver from "archiver";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const staging = path.join(root, "dist-staging", "maveoconnect");

function run(cmd, cwd, args) {
  const r = spawnSync(cmd, args, { cwd, stdio: "inherit", shell: process.platform === "win32" });
  if ((r.status ?? 1) !== 0) process.exit(r.status ?? 1);
}

function readVersion() {
  const cfg = fs.readFileSync(path.join(root, "plugin.cfg"), "utf8");
  const line = cfg.split(/\r?\n/).find((l) => l.startsWith("VERSION="));
  return line ? line.split("=")[1].trim() : "0.0.0";
}

/** Icons are generated by `npm run build:icons` before release:zip; this script is only
 *  responsible for the runtime bundle + ZIP packaging. Re-run icons here as a safety
 *  net for direct invocations (`node scripts/build-release.mjs`). */
run(process.execPath, root, [path.join(root, "scripts", "resize-plugin-icons.mjs")]);
const npmCmd = process.platform === "win32" ? "npm.cmd" : "npm";
run(npmCmd, root, ["run", "build"]);

const bundleSrc = path.join(root, "service", "dist", "service.mjs");
if (!fs.existsSync(bundleSrc)) {
  console.error("Missing service/dist/service.mjs — run npm run build first");
  process.exit(1);
}

const initScriptSrc = path.join(root, "daemon", "daemon");
if (!fs.existsSync(initScriptSrc)) {
  console.error("Missing daemon/daemon — required LoxBerry init script.");
  process.exit(1);
}

const sudoersSrc = path.join(root, "sudoers", "sudoers");
if (!fs.existsSync(sudoersSrc)) {
  console.error("Missing sudoers/sudoers — required for PHP-driven daemon restart.");
  process.exit(1);
}

if (fs.existsSync(staging)) fs.rmSync(staging, { recursive: true, force: true });
fs.mkdirSync(staging, { recursive: true });

const copyRel = (rel) => fs.cpSync(path.join(root, rel), path.join(staging, rel), { recursive: true });

[
  "webfrontend",
  "icons",
  "templates",
  "plugin.cfg",
  "postroot.sh",
  "postinstall.sh",
  "preupgrade.sh",
  "postupgrade.sh",
  "uninstall",
  "daemon",
  "sudoers",
].forEach(copyRel);

// Drop SVG masters from the ZIP — only PNGs are needed at runtime, and the SVGs are
// 1) larger than the PNGs combined, 2) only useful for the icon-build pipeline.
for (const svg of ["icon_source.svg", "icon_source_without_text.svg"]) {
  const svgPath = path.join(staging, "icons", svg);
  if (fs.existsSync(svgPath)) fs.rmSync(svgPath, { force: true });
}

// `bin/` in the ZIP becomes `/opt/loxberry/bin/plugins/maveoconnect/` on the device:
// LoxBerry copies the *contents* of `bin/`, not the wrapping `bin/` folder. So we ship
// the bundle as `bin/service.mjs` (no inner `maveoconnect/` subfolder).
fs.mkdirSync(path.join(staging, "bin"), { recursive: true });
fs.copyFileSync(bundleSrc, path.join(staging, "bin", "service.mjs"));

function walkFiles(dirBase, visitor) {
  for (const entry of fs.readdirSync(dirBase, { withFileTypes: true })) {
    const full = path.join(dirBase, entry.name);
    if (entry.isDirectory()) walkFiles(full, visitor);
    else visitor(full);
  }
}

function parentDirPrefixes(relWithSlashes) {
  const parts = relWithSlashes.split("/");
  const out = [];
  for (let i = 1; i < parts.length - 1; i++) out.push(parts.slice(0, i + 1).join("/") + "/");
  return out;
}

const fileEntries = [];
walkFiles(staging, (abs) => {
  const rel = path.relative(staging, abs).replaceAll("\\", "/");
  const zipPath = `maveoconnect/${rel}`;
  fileEntries.push({ abs, zipPath });
});

const dirPrefixes = new Set();
for (const { zipPath } of fileEntries) {
  for (const d of parentDirPrefixes(zipPath)) dirPrefixes.add(d);
}
const dirsOrdered = [...dirPrefixes].sort((a, b) => {
  const da = a.split("/").length;
  const db = b.split("/").length;
  if (da !== db) return da - db;
  return a.localeCompare(b);
});

// Files that must be executable inside the ZIP (LSB init + uninstall hook + sudoers
// loader expects 0644 for include lines — sudoers itself wants 0440 once installed but
// the ZIP entry mode only matters for shell-executable hooks; LoxBerry chmods sudoers).
const executableSet = new Set([
  "maveoconnect/daemon/daemon",
  "maveoconnect/uninstall/uninstall",
  "maveoconnect/postinstall.sh",
  "maveoconnect/postroot.sh",
  "maveoconnect/preupgrade.sh",
  "maveoconnect/postupgrade.sh",
]);

const version = readVersion();
const zipName = `loxberry-plugin-maveoconnect-${version}.zip`;
const distDir = path.join(root, "dist");
fs.mkdirSync(distDir, { recursive: true });
const zipPath = path.join(distDir, zipName);

await new Promise((resolve, reject) => {
  const output = fs.createWriteStream(zipPath);
  const archive = archiver("zip", { zlib: { level: 9 } });
  output.on("close", resolve);
  archive.on("error", reject);
  archive.pipe(output);
  for (const d of dirsOrdered) archive.append(Buffer.alloc(0), { name: d });
  for (const f of fileEntries) {
    const opts = executableSet.has(f.zipPath) ? { name: f.zipPath, mode: 0o755 } : { name: f.zipPath };
    archive.file(f.abs, opts);
  }
  archive.finalize();
});

console.log(`Wrote ${zipPath} (~${Math.round(fs.statSync(zipPath).size / 1024)} KB)`);
